### ISSUE TITLE
No Issues tab in the ossd-s23/group-5-extension repo

### ISSUE THREAD

**Issue by howtofly-lab** [cto234/group-5-extension#4]
@jz4721 @ishana-goyal @Pasindu3683 @jiawei-zhang-a I am writing Issues in this repo because there is no Issues tab in the repo linked in the "Browser extension presentations" page of the class wiki. I believe this can be fixed in the settings of the ossd-s23/group-5-extension repo.

**Comment by ishana-goyal** [comment]
Hi -- thank you for bringing this to our attention. I've added it now!
